# Run Snyk nightly to scan and report security issues.
name: Snyk Scan

# Job will run nightly at 02:05 EDT / 01:05 CDT
# Time below is UTC
on:
  schedule:
    - cron: "5 6 * * *"
  workflow_dispatch:

jobs:
  security-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          cache: 'maven'

      - name: Install snyk
        run: |
          wget -nv -nc https://static.snyk.io/cli/latest/snyk-linux -o snyk

      - name: Install modules
        run: |
          mvn -B -pl '!liquibase-dist' install -DskipTests=true

      - name: Run Snyk Test to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
#Do not want --all-projects despite the "Tip: Detected multiple supported manifests" because the root pom.xml includes the others
#Skipping liquibase-integration-tests because we couldn't get snyk to follow the dependency on liquibase-core:tests
          ./snyk config set api=$SNYK_TOKEN
          ./snyk test --fail-on=all --all-projects --severity-threshold=high --org=datical --policy-path=.snyk -- -B -Dscope=compile

#      - name: Run Snyk Monitor
#        uses: snyk/actions/maven@master
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#        with:
#          command: monitor
#          args: --org=datical --policy-path=.snyk -- -B  -pl '!liquibase-integration-tests'
#
#      - name: Slack Notification
#        if: ${{ failure() }}
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_CHANNEL: team-liquibase
#          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
#          SLACK_MESSAGE: "${{ github.job }}: ${{ job.status }} @here"
#          SLACK_USERNAME: "liquibot"
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#          MSG_MINIMAL: actions url
#          SLACK_ICON_EMOJI: ':liquibase:'
#          SLACK_LINK_NAMES: true
